import Image from 'next/image'
import React from 'react'
// as we have setup already, so simply setup
import { signIn } from 'next-auth/client'
import Head from 'next/head'

function Login() {
    return (
        <div className='grid place-items-center items-center'>
            <Head>
                <title>Facebook - Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                {/* for post picture */}
                <meta property="og:title" content="" />
                <meta property="og:type" content="" />
                <meta property="og:image" content="/facebook-Logo.png" />
                <meta name="twitter:card" content="summary_large_image" />

                <meta property="og:description" content="" />
                <meta name="twitter:image:alt" content="" />
            </Head>

            <Image src="https://links.papareact.com/t4i" height={400} width={400} objectFit='contain' />

            {/* onClick={signIn} >> signIn is the inbuilt function for logging in */}
            <h1 onClick={signIn} className='p-5 bg-blue-500 rounded-full text-white text-center cursor-pointer'>
                Login with Facebook</h1>
        </div>
    )
}

export default Login
